---
- name: Build XO
  ansible.builtin.command: "./upgrade-xo.sh"
  args:
    chdir: /opt/xen-orchestra
  register: result
  failed_when: result.rc != 0
  notify:
    - Install XO as service
    - Start Redis
    - Restart XO
    - Check that the XO-website boots up correctly

- name: Install XO as service
  become: true
  ansible.builtin.template:
    src: xo-server.service.j2
    dest: /etc/systemd/system/xo-server.service
    owner: root
    group: root
    mode: "0744"

- name: Start Redis
  tags: xo
  become: true
  ansible.builtin.systemd_service:
    name: redis
    daemon_reload: true
    enabled: true
    state: started

- name: Restart XO
  become: true
  ansible.builtin.systemd_service:
    name: xo-server
    enabled: true
    state: restarted
